clientTCP: clientTCP.c
	gcc clientTCP.c -o clientTCP.out

serverTCP: serverTCP.c
	gcc serverTCP.c -o serverTCP.out

clientUDP: clientUDP.c
	gcc clientUDP.c -o clientUDP.out

serverUDP: serverUDP.c
	gcc serverUDP.c -o serverUDP.out	
	